FROM openshift-spark-base

RUN yum install -y python-pymongo python-requests && \
    yum clean all

ADD caravan_master.py /

ENTRYPOINT ["/opt/spark/bin/spark-submit", \
	    "/caravan_master.py", \
	    "--port", "1984", \
            "--master", "spark://spark-master:7077", \
	    "--mongo", "mongo://???", \
	    "--rest", "http://???"]
