FROM openshift-spark-base

RUN yum install -y python-pymongo python-requests && \
    yum clean all

ADD caravan_master.py /
ADD start_master.sh /

ENTRYPOINT ["/start_master.sh", \
	    "spark-master-badt", \
	    "mongodb"]
